services:
  - type: web
    name: babychic-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: CORS_ORIGIN
        value: https://babychic-cameroun.netlify.app
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: UPLOAD_DIR
        value: uploads
      - key: MAX_FILE_SIZE
        value: 5242880
      - key: ADMIN_EMAIL
        value: admin@babychic.cm
      - key: ADMIN_PASSWORD
        value: admin123
      - key: ADMIN_FIRST_NAME
        value: Admin
      - key: ADMIN_LAST_NAME
        value: BabyChic
      # Database will be set manually in Render dashboard
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false

databases:
  - name: babychic-postgres
    plan: starter
    databaseName: babychic_db
    user: babychic_user
